ibpsa/project1-boptest-gym

boptestGymEnv.py
For https://github.com/ibpsa/project1-boptest-gym/issues/4.
=> Use weight for discomfort as local variable within compute_reward

boptestGymEnv.py
For https://github.com/ibpsa/project1-boptest-gym/issues/8.
=> Resolve bug with start_time and no excluding periods defined

boptestGymEnv.py, testing/test_boptestGymEnv.py
For https://github.com/ibpsa/project1-boptest-gym/issues/13.
=> Add excluding_periods as attribute instead of argument to reset.

boptestGymEnv.py, examples/run_baseline.py, examples/run_sample.py, examples/test_and_plot.py, testing/test_boptestGymEnv.py
For https://github.com/ibpsa/project1-boptest-gym/issues/28.
=> Issue13 cleanup testing

boptestGymEnv.py
For https://github.com/ibpsa/project1-boptest-gym/issues/30.
=> Redefine normalized action wrapper

boptestGymEnv.py
For https://github.com/ibpsa/project1-boptest-gym/issues/32.
=> Add custom reward functions

boptestGymEnv.py
For https://github.com/ibpsa/project1-boptest-gym/issues/18.
=> Change measurements keyword by observations keyword

boptestGymEnv.py, testing/test_boptestGymEnv.py
For https://github.com/ibpsa/project1-boptest-gym/issues/14.
=> Issue14 print

README.md
For https://github.com/ibpsa/project1-boptest-gym/issues/61.
=> Resolve typo

README.md, boptestGymEnv.py, examples/run_baseline.py, examples/run_sample.py, examples/run_save_callback.py, examples/run_variable_episode.py, examples/test_and_plot.py, examples/train_A2C.py, examples/train_A2C_predictive.py, examples/train_PPO2.py, examples/train_PPO2_predictive.py, testing/test_boptestGymEnv.py
For https://github.com/ibpsa/project1-boptest-gym/issues/56.
=> Modify simulation step keyword

boptestGymEnv.py
For https://github.com/ibpsa/project1-boptest-gym/issues/63.
=> Change default reward

examples/train_A2C.py
For https://github.com/ibpsa/project1-boptest-gym/issues/67.
=> Resolve typo in train_A2C

boptestGymEnv.py, examples/run_baseline.py, examples/test_and_plot.py, testing/references/summary_ref_0.json, testing/test_boptestGymEnv.py
For https://github.com/ibpsa/project1-boptest-gym/issues/57.
=> boptest scenario

boptestGymEnv.py
For https://github.com/ibpsa/project1-boptest-gym/issues/69.
=> Correct fore_n

.gitignore, examples/run_save_callback.py, examples/run_variable_episode.py, examples/train_A2C.py, examples/train_A2C_predictive.py, examples/train_PPO2.py, examples/train_PPO2_predictive.py, testing/test_boptestGymEnv.py
For https://github.com/ibpsa/project1-boptest-gym/issues/55.
=> Avoid tensorboard logs in testing

examples/test_and_plot.py
For https://github.com/ibpsa/project1-boptest-gym/issues/78.
=> Issue78 kpi to file

boptestGymEnv.py
For https://github.com/ibpsa/project1-boptest-gym/issues/80.
=> Save progress

README.md
For https://github.com/ibpsa/project1-boptest-gym/issues/91.
=> Add reference to README.md

boptestGymEnv.py
For https://github.com/ibpsa/project1-boptest-gym/issues/102.
=> Issue102 include bounds disc obs

docs/tutorials/CCAI Summer School 2022/Tutorial_2_Building_Control_with_RL_using_BOPTEST.ipynb
This is for https://github.com/ibpsa/project1-boptest-gym/issues/107.
=> Issue107 correct tutorial typos

boptestGymEnv.py, examples/run_baseline.py, examples/test_and_plot.py, examples/train_RL.py, testing/test_boptestGymEnv.py
For https://github.com/ibpsa/project1-boptest-gym/issues/109. @dhblum @kbenne @icupeiro FYI.
=> Issue109 update boptest030

boptestGymEnv.py, examples/run_baseline.py, examples/test_and_plot.py, examples/train_RL.py, testing/test_boptestGymEnv.py
For https://github.com/ibpsa/project1-boptest-gym/issues/111.
=> Issue111 update service to boptest v030

docs/tutorials/CCAI Summer School 2022/Tutorial_2_Building_Control_with_RL_using_BOPTEST.ipynb
For https://github.com/ibpsa/project1-boptest-gym/issues/113.
=> Issue113 update tutorial to boptest v030

examples/test_and_plot.py
=> Issue122 Check Wrapper class

boptestGymEnv.py, releasenotes.md, testing/Makefile
=> Issue127 forecast0

README.md, generateDockerComposeYml.py, parallel_BOPTESTgymTrain.py
=> Implementing parallel learning on BOPTEST-gym

.github/workflows/github-actions.yml, testing/Makefile
=> Issue152 Refactor to pull boptest_base image.

testing/Dockerfile
=> Update ubuntu and Python.
